# This code will build the Java project with Maven and check the code with Sonar Cloud

name: Build & Sonar Test
on:
  push:
    branches:
      - main
  pull_request:
    types: [assigned, edited, synchronize, reopened, review_requested]
jobs:
  build:
    name: Build & Test with Sonar Cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        # Adding profile javafx to download javafx depedencies in java 11 environment
        run: mvn -B -Pjavafx verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar